name: Terraform CI

on:
  push:
    branches:
      - feature/infraestructura
    paths:
      - 'infra/**'
  pull_request:
    paths:
      - 'infra/**'

jobs:
  terraform:
    name: Validar y aplicar infraestructura
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Inicializar Terraform
        run: terraform init

      - name: Verificar formato (terraform fmt)
        run: terraform fmt -check -recursive

      - name: Validar sintaxis (terraform validate)
        run: terraform validate

      - name: Plan de Terraform
        run: terraform plan

      - name: Aplicar infraestructura (solo en rama dev)
        if: github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve
