name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pytest y requests
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start Docker containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for vote service to be ready
        run: |
          echo "Esperando a que vote esté disponible..."
          for i in {1..10}; do
            if curl -s http://localhost:5000/; then
              echo "✅ Vote está listo"
              break
            fi
            echo "Intento $i fallido, esperando 3s..."
            sleep 3
          done

      - name: Run tests
        run: python -m pytest vote/test/test_vote.py

      - name: Stop Docker containers
        if: always()
        run: docker-compose down
